config/routes.rb
Rails.application.routes.draw do
  root 'duck#search'
	
  get 'match/showmatches'

  get 'match/showdetail'
  get 'match/showdetail/:id' => 'match#showdetail'

  get 'match/showreplay'

  post 'match/pondmatch' => 'match#singlefight'
  
  post 'match/fightover'

  get 'match/multifight'

  get 'match/loopfight'

  get 'duck/myscript'

  get 'duck/pondtest' => 'duck#createscript'
  
  get 'duck/editscript'
  
  get 'duck/editscript/:id' => 'duck#editscript'
  
  post 'duck/savescript'
  
  get 'duck/deletescript'
  get 'duck/deletescript/:id' => 'duck#deletescript'

  get 'duck/search'
  
  post 'duck/search' => 'duck#search_submit'

  get 'account/regist' => 'account#regist_new'
  
  post 'account/regist' => 'account#regist_submit'

  get 'account/login' => 'account#login_new'
  
  post 'account/login' => 'account#login_submit'

  get 'account/logout' 
  
  get 'account/info'
  get 'account/info/:id' => 'account#info'
  
  get 'account/changepw'
  post 'account/changepw' => 'account#changepw_submit'
  
  get 'account/editinfo' => 'account#info_edit'
  
  post 'account/editinfo' => 'account#info_submit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/duck.rb
class Duck < ApplicationRecord

  belongs_to :user
  has_many :fight_results
  has_many :fights, through: :fight_results

  def win_rate
    all_count=win_count+lose_count+draw_count
	if all_count <= 0
	  return 0.00
	else 
	
      v=win_count*100.0/all_count
	  return '%.2f' % v
	end
  end
  
  def savescript(script)
	script.gsub!(/\r/u,'\\r')
	script.gsub!(/\n/u,'\\n')
	self.script=script
  end
  

end

app/controllers/duck_controller.rb
class DuckController < ApplicationController
  before_action :check_user
  protect_from_forgery :except => :savescript  
  
  def myscript
    @user=User.find_by(id:session[:user_id])
	@myducks=@user.myducks.order(updated_at: :desc)
  end

  def createscript
    if flash[:is_edit].nil?
	  session[:script_id]=nil
	end
	if not session[:script_id].nil?
		@duck=Duck.find_by(id:session[:script_id])
		@duck.script=@duck.script.gsub(/\r\n/,'\\r\\n')
	end
  end
  
  def savescript
    if session[:script_id].nil?
      @duck=Duck.new
	  @duck.user_id=session[:user_id]
	else 
	  @duck=Duck.find_by(id:session[:script_id])
	end
	if params[:script_is_block]=='1'
		@duck.is_block=true
	else
	    @duck.is_block=false
	end
	if params[:script_is_public]=='1'
	    @duck.is_public=true
	else
	    @duck.is_public=false
	end
	@duck.is_delete=false
	@duck.win_count=0
	@duck.lose_count=0
	@duck.draw_count=0
	@duck.name=params[:script_name]
	@duck.savescript params[:script_script]
	
	
	if @duck.save
	  render plain: '保存成功'
	  return
	  # redirect_to duck_myscript_path, flash:{info: '保存成功'}
	else 
	  render plain: '保存失败，请检查信息'
	  return
	  # redirect_to duck_myscript_path, flash:{info: '保存失败，请检查信息'}
	end
	
  end

  def editscript
    @duck=Duck.find_by(id:params[:id])
	if @duck.nil?
	  redirect_to duck_myscript_path
	else
	  session[:script_id]=params[:id]
	  redirect_to duck_pondtest_path, flash:{is_edit: true}
	end
  end

  def deletescript
    @duck=Duck.find_by(id:params[:id])
	if @duck.nil?
	  redirect_to duck_myscript_path, flash:{info: '不存在此脚本'}
	else
	  @duck.is_delete=true
	  @duck.save
	  redirect_to duck_myscript_path, flash:{info: '删除成功'}
	end
  end

  def search
    @user=User.find_by(id:session[:user_id])
	@myducks=@user.ducks
	@ducks=Duck.where(is_delete:false,is_public:true).order(updated_at: :desc)
  end
  
    
  private
  
  def check_user
    if session[:user_id].nil?
      redirect_to account_login_path, flash: {danger: '请登录'}
    end
  end
  
  
  
end

app/helpers/duck_helper.rb
module DuckHelper
end

app/views/duck/createscript.html.erb
<div class="wrapper">
<head>
  <script src="/third-party/ace/ace.js"></script>
  <script src="/common/boot.js"></script>
  <script src="/common/duckchange.js"></script>
  <link rel="stylesheet" href="/common/common.css">
  <link rel="stylesheet" href="/pond/style.css">
  <link rel="stylesheet" href="/pond/duck/style.css">
 </head> 
  
	

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
     
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        训练塘
      </h1>
		  <div class="form-group">  
		<form class="form-inline" onkeydown="if(event.keyCode==13){return false;}" role="form">
			  <div class="form-group">
				<label for="name">当前加载的脚本：
				<% if @duck.nil? %>
				  (未命名)
				<% else %>
				   <%=@duck.name %>
				<% end %>
				</label>
				<input type="text" class="form-control" id="sname" value='<% if session[:script_id].nil? %><% else %><%=@duck.name %><% end %>' placeholder="请为脚本命名">
				<input type="checkbox" id="sispublic" name="ispublic" <%if @duck.nil? or @duck.is_public=true%><%="checked='checked'"%><%end%> >脚本公开</input>
			  </div>
			  <button type="button" onclick="saveScript()" class="btn btn-success">保存脚本</button>
		</form>
		
		
	</div>  
	
	<div class="row">
		<form class="form-inline" onkeydown="if(event.keyCode==13){return false;}" role="form">
			<div class="col-sm-3">
			     <div class="form-group">
                  <label>选手1</label>
                  <select class="form-control" id="player1">
				  <option value='0'>-----无-----</option>
                    <option value='-1'>兔子</option>
                    <option value='-2'>计数者</option>
                    <option value='-3'>堡垒</option>
                    <option value='-4'>狙击手</option>
                    <option value='1'>(你自己)</option>
                  </select>
                </div>
			</div>
			<div class="col-sm-3">
			     <div class="form-group">
                  <label>选手2</label>
                  <select class="form-control" id="player2">
				  <option value='0'>-----无-----</option>
                    <option value='-1'>兔子</option>
                    <option value='-2'>计数者</option>
                    <option value='-3'>堡垒</option>
                    <option value='-4'>狙击手</option>
					<option value='1'>(你自己)</option>
                  </select>
                </div>
			</div>
						<div class="col-sm-3">
			     <div class="form-group">
                  <label>选手3</label>
                  <select class="form-control" id="player3">
				  <option value='0'>-----无-----</option>
                    <option value='-1'>兔子</option>
                    <option value='-2'>计数者</option>
                    <option value='-3'>堡垒</option>
                    <option value='-4'>狙击手</option>
					<option value='1'>(你自己)</option>
                  </select>
                </div>
			</div>
						<div class="col-sm-3">
			     <div class="form-group">
                  <label>选手4</label>
                  <select class="form-control" id="player4">
				  <option value='0'>-----无-----</option>
                    <option value='-1'>兔子</option>
                    <option value='-2'>计数者</option>
                    <option value='-3'>堡垒</option>
                    <option value='-4'>狙击手</option>
					<option value='1'>(你自己)</option>
                  </select>
                </div>
			</div>
		</form>
		
		</div>
    </section>

    <!-- Main content -->
    <section class="content" style="margin-top:50px">
		
      <div id="pond_game_content" class="row">
	   
	  </div>

    </section>
    <!-- /.content -->
  
  <!-- 
  {include file="footer" /}-->
  </div>
</div>
<!-- ./wrapper -->


<script>


$("select#player1").change(function(){
     //console.log($(this).val());
	 updateUser();
 });
 $("select#player2").change(function(){
     //console.log($(this).val());
	 updateUser();
 });
 $("select#player3").change(function(){
     //console.log($(this).val());
	 updateUser();
 });
 $("select#player4").change(function(){
     //console.log($(this).val());
	 updateUser();
 }); 
 
 var HtmlUtil = {
      htmlEncode:function (html){
         var temp = document.createElement ("div");
          (temp.textContent != undefined ) ? (temp.textContent = html) : (temp.innerText = html);
          var output = temp.innerHTML;
         temp = null;
         return output;
     },
     htmlDecode:function (text){
         var temp = document.createElement("div");
         temp.innerHTML = text;
         var output = temp.innerText || temp.textContent;
         temp = null;
         return output;
     }
 };

 
function setScriptData() { 
    script='<%if not @duck.nil? %><%=@duck.script%><%end%>'
	script=HtmlUtil.htmlDecode(script.replace(/\\n/g, "\n").replace(/\\r/g, "\r"));
	
	if(<%if @duck.nil? or not @duck.is_block %><%=0%><%else%><%=1%><%end%>==0){
		Pond.Duck.changeTab(1);
		Pond.Duck.blocksEnabled_ = false;
		BlocklyInterface.editor['setValue'](script, -1);
	}else{
		Pond.Duck.changeTab(0);
	    //console.log("block!");
		Pond.Duck.blocksEnabled_ = true;
		var xml = Blockly.Xml.textToDom(script);
		// Clear the workspace to avoid merge.
		BlocklyGames.workspace.clear();
		Blockly.Xml.domToWorkspace(xml, BlocklyGames.workspace);
		BlocklyGames.workspace.clearUndo();
		
		
	}
  
}
 
 function getUserScript(){
 		//console.log(Pond.Duck.blocksEnabled_)
         if (Pond.Duck.blocksEnabled_) {
		    
		    var xml = Blockly.Xml.workspaceToDom(BlocklyGames.workspace);
			var xmlData = Blockly.Xml.domToText(xml);
			//return xmlData;
           return xmlData.replace(new RegExp("'",'gm'),'');
         } else {
           return BlocklyInterface.editor['getValue']().replace(new RegExp("'",'gm'),'"');
		   }
 
 }
 
 function saveScript(){
 if ($('#sispublic').attr('checked')) {
    sispublic=1
}else{
	sispublic=0
}
//console.log(sispublic)
	script=getUserScript();//return false;
	//script=HtmlUtil.htmlEncode(script);
	//console.log(script);
	sname=$("#sname").val().replace(new RegExp("'",'gm'),'');
	if(Pond.Duck.blocksEnabled_==true)isBlock=1;
	else isBlock=0;
	
	if(sname.length<=0){
		alert("请输入要保存的脚本名称");
		return false;
	}
	
	
	//if(!confirm("将覆盖你的同名脚本（"+sname+"），确定吗？")){
	//	return false;
	//}
	
	
	$.ajax({
		type:"POST",
		url:"<%=duck_savescript_path%>",
		dataType:"json",
		data:{
			script_name:sname,
			script_script:script,
			script_is_block:isBlock,
			script_is_public:sispublic
			},
		success:function (msg)
		{
			//console.log(msg.responseText);
			if (msg.responseText=="保存成功")
			{
				//success
				alert("保存成功");
				
			}else
			{
				//error
				alert("保存出错");
				
			}
			
			return false;

		},
		error:function (msg)
		{
			//console.log(msg);
			if (msg.responseText=="保存成功")
			{
				//success
				alert("保存成功");
				
			}else
			{
				//error
				alert("保存出错");
				
			}
			
			return false;

		}
	});
	
	
	return false;
 }

</script>

app/views/duck/myscript.html.erb
<div class="wrapper">
  <div class="content-wrapper">
    <section class="content-header">
      <h1>
        我的脚本
      </h1>
    </section>

    <!-- Main content -->
    <section class="content">
      
      <!-- Main row -->
      <div class="row">
        <div class="col-xs-12 table-responsive">
          <table class="table table-striped">
            <thead>
            <tr>
              <th>名字</th>
              <th>作者</th>
              <th>发布时间</th>
			  <th>是否公开</th>
			  <th>是否为js</th>
			  <th>胜率</th>
              <th>操作</th>
            </tr>
            </thead>
            <tbody>
			
			<% for d in @myducks %>
			<tr>
				<td><%=d.name%></td>
				<td><a href='<%=account_info_path+"/"+d.user.id.to_s%>'><%=d.user.nickname%></a></td>
				<td><%=d.updated_at.strftime('%Y-%m-%d %H:%M')%></td>
				<td><%if d.is_public%><%='是'%><%else%><%='否'%><%end%></td>
				<td><%if !d.is_block%><%='是'%><%else%><%='否'%><%end%></td>
				<td><%=d.win_rate%>%</td>
				<td><a class='btn btn-warning'  href='javascript:chooseSelfDuck("<%=d.id%>");'>比试</a>
					<a class='btn btn-success'  href='<%=duck_editscript_path+"/"+d.id.to_s%>'>编辑</a>
					<a class='btn btn-danger'  href='javascript:deleteSelfDuck("<%=d.id%>")'>删除</a>
				</td>
				
				
			</tr>
			<%end%>
			

            </tbody>
          </table>
        </div>
        <!-- /.col -->
		

      </div>
      <!-- /.row -->
	  
	  

	
	
    </section>
    <!-- /.content -->
  </div>
  <!-- 
  {include file="footer" /}-->

  
</div>
<!-- ./wrapper -->

	  <div class="modal fade" id="chooseDuck" tabindex="-1" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
					&times;
				</button>
				<h4 class="modal-title" id="myModalLabel">
					选择你要作战的小鸭子AI
				</h4>
			</div>
			<div class="modal-body">
				<select class="form-control" id="myduck">
				    <% for d in @myducks %>
					
						 <option value='<%=d.id%>'><%=d.name%></option>
					<%end%>
				   
				</select>
			</div>
			<div class="modal-footer">
				<a href="javascript:startMatch();" class="btn btn-success">开始比赛</a>
				<a href="#" class="btn" data-dismiss="modal">关闭</a>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal -->
</div>


	
<script>

function post(URL, PARAMS) {
  console.log(URL);
  var temp = document.createElement("form");
  temp.action = URL;
  temp.method = "post";
  temp.style.display = "none";
  for (var x in PARAMS) {
    var opt = document.createElement("textarea");
    opt.name = x;
    opt.value = PARAMS[x];
    // alert(opt.name)
    temp.appendChild(opt);
  }
  document.body.appendChild(temp);
  temp.submit();
  return temp;
}

var targetid;
function startMatch(){
	myid=$("select#myduck").val();console.log(myid);
	post('<%=match_pondmatch_path%>',{ id1:myid,id2:window.targetid });
	return false;
}

function chooseSelfDuck(id){
	if($("select#myduck").val()==null){
	
		// dont have any duck
		alert("你还没有创建过任何脚本，所以无法进行比赛。去“训练塘”创建你的小鸭子脚本吧！");
		return false;
	}
	window.targetid=id;
	$("#chooseDuck").modal('show');  
	return false;
}

function deleteSelfDuck(id){
	if(confirm("确定要删除此脚本吗？")){
		window.location.href='<%=duck_deletescript_path+"/"%>'+id;
	}
	return false;
}



</script>

app/views/duck/search.html.erb
<div class="wrapper">
  <div class="content-wrapper">
    <section class="content-header">
      <h1>
        对战脚本列表
        <small>大家公开的小鸭子脚本</small>
      </h1>
    </section>

    <!-- Main content -->
    <section class="content">
      
      <!-- Main row -->
      <div class="row">
        <div class="col-xs-12 table-responsive">
          <table class="table table-striped">
            <thead>
            <tr>
              <th>名字</th>
              <th>作者</th>
              <th>发布时间</th>
			  <th>胜率</th>
              <th>操作</th>
            </tr>
            </thead>
            <tbody>
			
			<% for d in @ducks %>
			<tr>
				<td><%=d.name%></td>
				<td><a href='<%=account_info_path+"/"+d.user.id.to_s%>'><%=d.user.nickname%></a></td>
				<td><%=d.updated_at.strftime('%Y-%m-%d %H:%M')%></td>
				<td><%=d.win_rate%>%</td>
				<td><a class='btn btn-warning'  href='javascript:chooseSelfDuck("<%=d.id%>");'>比试</a>
				<% if d.user.id==session[:user_id]%>
					<a class='btn btn-success'  href='<%=duck_editscript_path+"/"+d.id.to_s%>'>编辑</a>
				<%end%>
				</td>
				
				
			</tr>
			<%end%>
			

            </tbody>
          </table>
        </div>
        <!-- /.col -->
		

      </div>
      <!-- /.row -->
	  
	  

	
	
    </section>
    <!-- /.content -->
  </div>
  <!-- 
  {include file="footer" /}-->

  
</div>
<!-- ./wrapper -->

	  <div class="modal fade" id="chooseDuck" tabindex="-1" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
					&times;
				</button>
				<h4 class="modal-title" id="myModalLabel">
					选择你要作战的小鸭子AI
				</h4>
			</div>
			<div class="modal-body">
				<select class="form-control" id="myduck">
				    <% for d in @myducks %>
					
						 <option value='<%=d.id%>'><%=d.name%></option>
					<%end%>
				   
				</select>
			</div>
			<div class="modal-footer">
				<a href="javascript:startMatch();" class="btn btn-success">开始比赛</a>
				<a href="#" class="btn" data-dismiss="modal">关闭</a>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal -->
</div>


	
<script>

function post(URL, PARAMS) {
  console.log(URL);
  var temp = document.createElement("form");
  temp.action = URL;
  temp.method = "post";
  temp.style.display = "none";
  for (var x in PARAMS) {
    var opt = document.createElement("textarea");
    opt.name = x;
    opt.value = PARAMS[x];
    // alert(opt.name)
    temp.appendChild(opt);
  }
  document.body.appendChild(temp);
  temp.submit();
  return temp;
}

var targetid;
function startMatch(){
	myid=$("select#myduck").val();console.log(myid);
	post('<%=match_pondmatch_path%>',{ id1:myid,id2:window.targetid });
	return false;
}

function chooseSelfDuck(id){
	if($("select#myduck").val()==null){
	
		// dont have any duck
		alert("你还没有创建过任何脚本，所以无法进行比赛。去“训练塘”创建你的小鸭子脚本吧！");
		return false;
	}
	window.targetid=id;
	$("#chooseDuck").modal('show');  
	return false;
}

function editSelfDuck(id){
	get('<%=duck_editscript_path+"/"%>'+id);
	return false;
}

</script>