config/routes.rb
Rails.application.routes.draw do
  root 'duck#search'
	
  get 'match/showmatches'

  get 'match/showdetail'
  get 'match/showdetail/:id' => 'match#showdetail'

  get 'match/showreplay'

  post 'match/pondmatch' => 'match#singlefight'
  
  post 'match/fightover'

  get 'match/multifight'

  get 'match/loopfight'

  get 'duck/myscript'

  get 'duck/pondtest' => 'duck#createscript'
  
  get 'duck/editscript'
  
  get 'duck/editscript/:id' => 'duck#editscript'
  
  post 'duck/savescript'
  
  get 'duck/deletescript'
  get 'duck/deletescript/:id' => 'duck#deletescript'

  get 'duck/search'
  
  post 'duck/search' => 'duck#search_submit'

  get 'account/regist' => 'account#regist_new'
  
  post 'account/regist' => 'account#regist_submit'

  get 'account/login' => 'account#login_new'
  
  post 'account/login' => 'account#login_submit'

  get 'account/logout' 
  
  get 'account/info'
  get 'account/info/:id' => 'account#info'
  
  get 'account/changepw'
  post 'account/changepw' => 'account#changepw_submit'
  
  get 'account/editinfo' => 'account#info_edit'
  
  post 'account/editinfo' => 'account#info_submit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/match.rb
class Match < ApplicationRecord
  has_many :fights
  belongs_to :user
end

app/controllers/match_controller.rb
class MatchController < ApplicationController
  before_action :check_user
  protect_from_forgery :except => [:singlefight,:fightover]
  

  def showmatches
	@matches=Match.where(is_end: true).order(updated_at: :desc)
  end

  def showdetail
    @user=User.find(session[:user_id])
	@fight=Fight.find_by(id: params[:id])
	if @fight.nil?
	  redirect_to match_showmatches_path
	else
	  @match=@fight.match
	  
	end
  end

  def showreplay
  end

  def singlefight
    @duck1=Duck.find_by(id:params[:id1])
	@duck2=Duck.find_by(id:params[:id2])
	if @duck1.nil? or @duck2.nil?
	  redirect_to duck_search_path
	  return
	end
	@duck1.script=@duck1.script.gsub(/\r\n/,'\\r\\n')
	@duck2.script=@duck2.script.gsub(/\r\n/,'\\r\\n')
	@ducks=Array.new
	@ducks.push(@duck1).push(@duck2)
	
  end
  
  def singlefight_submit
  end

  def multifight
  end

  def loopfight
  end

  def fightover
    jdata=params[:all]
	data=JSON.parse(jdata)
    user=User.find(session[:user_id])
	if not data.nil? and data.size >= 2
	  match=Match.new
	  match.is_end=true
	  match.user=user
	  if !match.save
	    render plain: "cannot save"
	    return
	  end
	  fight=Fight.new
	  fight.tag = 1
	  fight.match=match
	  fight.user=user
      fight.save

	  str=''
	  
	  if data.size==2
	    # 1v1
		  duck1=Duck.find_by(id: data[0][0])
		  duck2=Duck.find_by(id: data[1][0])
		  
		  result1=FightResult.new
		  result1.fight=fight
		  result1.duck=duck1
		  result1.live_time=data[0][1].to_f
		  result1.hp_left=data[0][2].to_f
		  result1.dmg=data[0][3].to_f
		  result1.save
		  
		  result2=FightResult.new
		  result2.fight=fight
		  result2.duck=duck2
		  result2.live_time=data[1][1].to_f
		  result2.hp_left=data[1][2].to_f
		  result2.dmg=data[1][3].to_f
		  result2.save
		  
		  win=false
		  draw=false
		  if result1.hp_left == result2.hp_left
		    draw=true
			win=false
		  elsif result1.hp_left>result2.hp_left
		    win=true
			draw=false
		  else 
		    win=false
			draw=false
		  end
		  
		  # 修改duck的自己的战绩记录
		  if draw
		    duck1.draw_count+=1
			duck2.draw_count+=1
		  elsif win
		    duck1.win_count+=1
			duck2.lose_count+=1
		  else
		    duck1.lose_count+=1
			duck2.win_count+=1
		  end
		  duck1.record_timestamps=false
		  duck2.record_timestamps=false
		  duck1.save
		  duck2.save

			# 挑战者
			str="用"+duck1.name+"挑战了"+duck2.user.nickname+"的"+duck2.name+"，"
			if draw
			  str=str+"两人菜鸡互啄，打成了平手。"
			elsif win
			  str=str+"并击败了对方。"
			else
			  str=str+"结果被对方击败了。"
			end
			log=UserLog.new
			log.user=duck1.user
			log.message=str
			log.fight=fight
			log.save

			# 被挑战者
			str=duck1.user.nickname+"用他的"+duck1.name+"向"+duck2.name+"发起了挑战，"
			if draw
			  str=str+"结果两人菜鸡互啄，打成了平手。"
			elsif win
			  str=str+"并成功打败了"+duck2.name+"。"
			else
			  str=str+"结果被"+duck2.name+"击败了。"
			end
		    log=UserLog.new
			log.user=duck2.user
			log.message=str
			log.fight=fight
			log.save
	  else
	    # 1vN
		  for d in data
			duck=Duck.find_by(id:d[0])
			fightresult=FightResult.new
			fightresult.fight=fight
			fightresult.duck=duck
			fightresult.live_time=d[1].to_f
			fightresult.hp_left=d[2].to_f
			fightresult.dmg=d[3].to_f
			fightresult.save
			
			str=duck.user.nickname+"参加了一场"+data.size+"人混战，"
			if d[2].to_f <= 0
			  str=str+"结果没能活到最后。"
			else
			  str=str+"结果以"+d[2].to_f+"点生命值站到了最后。恭喜！"
			end
		    log=UserLog.new
			log.user=duck.user
			log.message=str
			log.fight=fight
			log.save
		  end
	  end
	  
	  
	end
    render plain: "success"
  end
  
  
  
  
  
    private
  
  def check_user
    if session[:user_id].nil?
      redirect_to account_login_path, flash: {danger: '请登录'}
    end
  end
  
end

app/helpers/match_helper.rb
module MatchHelper
end

app/views/match/loopfight.html.erb
<h1>Match#loopfight</h1>
<p>Find me in app/views/match/loopfight.html.erb</p>

app/views/match/multifight.html.erb
<h1>Match#multifight</h1>
<p>Find me in app/views/match/multifight.html.erb</p>

app/views/match/showdetail.html.erb
<div class="wrapper">
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        比赛详情
      </h1>
    </section>

    <!-- Main content -->
    <section class="content">
      <% if flash[:danger] %>
  <p class="box"><%= flash[:danger] %></p>
<%end %>


<%= form_for(:account, url: account_changepw_path, method: :post, html: {role: 'form'}) do |f| %>
	  <div class="form-group has-feedback">
        <label>发起人： <%=@match.user.nickname%> </label>
      </div>
	  <div class="form-group has-feedback">
        <label>类型： <%=@match.tag%>1v1对战 </label>
      </div>
      <div class="form-group has-feedback">
        <label>开始时间： <%=@match.created_at%> </label>
      </div>
	  <div class="form-group has-feedback">
        <label>结束时间： <%=@match.updated_at%> </label>
      </div>
	  <div class="form-group has-feedback">
        <label>比赛结果： </label>
		<% count=1 %>
		<% for fight in @match.fights %>
		<br>场次<%=count%><%count+=1%>：
		
		
		    <table class="table table-striped">
            <thead>
            <tr>
              <th>对战者</th>
			  <th>作者</th>
			  <th>存活时间</th>
			  <th>生命剩余</th>
			  <th>造成伤害</th>
            </tr>
            </thead>
            <tbody>
			<% for r in fight.fight_results %>
			<tr>
				<td><%=r.duck.name%></td>
				<td><%=r.duck.user.nickname%></td>
				<td><%=r.live_time%></td>
				<td><%=r.hp_left%>%</td>
				<td><%=r.dmg%>%</td>
			</tr>
			<%end%>
			
            </tbody>
          </table>
		 <%end%>
      </div>
      <div class="row">
        <div class="col-xs-3">
        </div>
        <!-- /.col -->
        <div class="col-xs-6">
       <button type="button" class="btn btn-default btn-block btn-flat" onclick="javascript:history.go(-1);">返回</button>
	   </div>
        <!-- /.col -->
      </div>

  
<% end %>


    </section>
    <!-- /.content -->
  </div>

</div>
<!-- ./wrapper -->

app/views/match/showmatches.html.erb
<div class="wrapper">
  <div class="content-wrapper">
    <section class="content-header">
      <h1>
        比赛记录
        <small></small>
      </h1>
    </section>

    <!-- Main content -->
    <section class="content">
      
      <!-- Main row -->
      <div class="row">
        <div class="col-xs-12 table-responsive">
          <table class="table table-striped">
            <thead>
            <tr>
              <th>发起人</th>
              <th>开始时间</th>
			  <th>结束时间</th>
              <th>操作</th>
            </tr>
            </thead>
            <tbody>
			
			<% for match in @matches %>
			<tr>
				<td><a href='<%=account_info_path+"/"+match.user.id.to_s%>'><%=match.user.nickname%></a></td>
				<td><%=match.created_at.strftime('%Y-%m-%d %H:%M')%></td>
				<td><%=match.updated_at.strftime('%Y-%m-%d %H:%M')%>%</td>
				<td><a class='btn btn-primary'  href='<%=match_showdetail_path+"/"+match.id.to_s%>'>查看详情</a>
				</td>
				
				
			</tr>
			<%end%>
			

            </tbody>
          </table>
        </div>
        <!-- /.col -->
		

      </div>
      <!-- /.row -->
	  
	  

	
	
    </section>
    <!-- /.content -->
  </div>
  <!-- 
  {include file="footer" /}-->

  
</div>

app/views/match/showreplay.html.erb
<h1>Match#showreplay</h1>
<p>Find me in app/views/match/showreplay.html.erb</p>

app/views/match/singlefight.html.erb
<head>
  <link rel="stylesheet" href="/common/common.css">
  <link rel="stylesheet" href="/pond/style.css">
  <link rel="stylesheet" href="/pond/duck/style.css">
</head>


<div class="wrapper">

	
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        <%=@duck1.name%>&nbsp;&nbsp;&nbsp;&nbsp;VS&nbsp;&nbsp;&nbsp;&nbsp;<%=@duck2.name%>
      </h1>
		<p id="leftTime">剩余时间 : 30 秒</p>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
	    <div class="col-md-4"  id="pond_game_content">
		
		</div><div show="hidden" id="blockly"></div>
		<div class="col-md-8">
			<div class="box box-success direct-chat direct-chat-success" >
                <div class="box-header with-border">
                  <h3 class="box-title">战斗过程</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body" >
                  <div class="direct-chat-messages" id="matchdetail" style="min-height:370px">
                     <!-- <div class="direct-chat-info clearfix">战斗234</div> -->
					 
                <!-- /.box-footer-->
				  </div>
				  <!--/.direct-chat -->
				</div>
			</div>
		  </div>
		</div>
    </section>
    <!-- /.content -->
  </div>
  <!-- 
  {include file="footer" /}-->

  
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<script>

var height=350;
function print(str){
	$("#matchdetail").append('<div class="direct-chat-info clearfix">'+str+'</div>');
	height+=20;
	$("#matchdetail").scrollTop(height); 
	
}

function setTime(time){
	if(time<=0)time=0;
	$("#leftTime").text("剩余时间: "+time+" 秒")
}


 var HtmlUtil = {
      htmlEncode:function (html){
         var temp = document.createElement ("div");
          (temp.textContent != undefined ) ? (temp.textContent = html) : (temp.innerText = html);
          var output = temp.innerHTML;
         temp = null;
         return output;
     },
     htmlDecode:function (text){
         var temp = document.createElement("div");
         temp.innerHTML = text;
         var output = temp.innerText || temp.textContent;
         temp = null;
         return output;
     }
 };
 
 

 function getId(name){
    t=new Array();
	<% for duck in @ducks %>
	  dr=new Array();
	  dr.push('<%=duck.id%>');
	  dr.push('<%=duck.name%>');
	  t.push(dr);
	<%end%>
    
	
	for(index in t){
	  if(t[index][1]==name){
	    return t[index][0];
	  }
	}
	return '';
 }

function gameover(){
	//console.log(Pond.Battle.RANK);
	
	result=new Array();
	
	//id,time,hp,dmg
	<% for duck in @ducks %>

	<%end%>
	
	for(index in Pond.Battle.RANK){
		  
	  
		duck=Pond.Battle.RANK[index];
		id=getId(duck.name);
		
		dr=new Array();
	    dr.push(id);
	    dr.push(0);
	    dr.push(100-duck.damage);
	    dr.push(0);
	    result.push(dr);
	}
	
	//console.log(result);
	
	
	
    winner=Pond.Battle.RANK[0];
	winnerIndex=winner.visualizationIndex;
	winnerName=winner.name;
	winnerHP=100-winner.damage;
	
	loser=Pond.Battle.RANK[1];
	loserIndex=loser.visualizationIndex;
	loserName=loser.name;
	loserHP=100-loser.damage;
	
	winnerHP=Math.round(winnerHP * 100) / 100;
	loserHP=Math.round(loserHP * 100) / 100;
	
	if(winnerHP>loserHP){
		//someone win
		print((winnerIndex+1)+"号选手："+winnerName+" 取得胜利！给对手造成"+(100-loserHP)+"点伤害，自己还剩下"+winnerHP+"点生命值");
		switch(winnerIndex+1){
			case 1:score1=1;score2=0;break;
			case 2:score1=0;score2=1;break;
			default:score1=0;score2=0;break;
		}
	}else{
		//draw match
		print((winnerIndex+1)+"号选手："+winnerName+" 和"+(loserIndex+1)+"号选手："+loserName+" 菜鸡互啄，打了个平手。");
		score1=0;
		score2=0;
	}
	id1=<%=@duck1.id%>;
	id2=<%=@duck2.id%>;
    
	
	result=JSON.stringify(result);

	console.log(result);
	$.ajax({
		type:"POST",
		url:"<%=match_fightover_path%>",
		dataType:"json",
		data:{
			id1:id1,
			id2:id2,
			score1:score1,
			score2:score2,
			all:result
			},
		success:function (msg)
		{
			print("(比赛结束。请自行返回之前的页面)");
			return false;

		},
		error:function (msg)
		{
			console.log(msg);
			print("(比赛结束。请自行返回之前的页面)");
			return false;

		}
	});
}

 function getUserScript(script,isBlock){
		script=script.replace(/\\n/g, "\n").replace(/\\r/g, "\r")
        script=HtmlUtil.htmlDecode(script);
 		//console.log(script);
         if (isBlock==1) {
		    
		    var xml = Blockly.Xml.textToDom(script);
		    Blockly.Xml.domToWorkspace(xml, BlocklyGames.workspace);
			xmlData=Blockly.JavaScript.workspaceToCode(BlocklyGames.workspace);
           return xmlData.replace(new RegExp("'",'gm'),'');
         } else {
           return script.replace(new RegExp("'",'gm'),'"');
		   }
 
 }


function initMatch(){
BlocklyGames.workspace = Blockly.inject('blockly',
      {'media': '/third-party/blockly/media/',
       'rtl': false,
       'toolbox': false,
       'trashcan': false,
       'zoom': null});
	   
	   
	script1=getUserScript('<%=@duck1.script%>',<%=@duck1.is_block%>);
	//if({$isBlock1})
	script2=getUserScript('<%=@duck2.script%>',<%=@duck2.is_block%>);
	name1='<%=@duck1.name%>';
	name2='<%=@duck2.name%>';
	//console.log(script1);
	//console.log(script2);
	Pond.Battle.addAvatar(name1, script1, new goog.math.Coordinate(20, 50), 0);
	Pond.Battle.addAvatar(name2, script2, new goog.math.Coordinate(80, 50), 0);
	
	var time=3;
  var timer = setInterval(function (){
  
	if(time<=0){
		print("开始比赛");
	}else{
		print("还剩"+time+"秒开始比赛");
	}
    
	time-=1;
	
	if(time<=-1){
		
		clearInterval(timer);
		Pond.execute();
		return;
	}
    
  }, 1000);
}

</script>
  <script src="/third-party/ace/ace.js"></script>
  <script src="/common/boot.js"></script>
   <script src="/common/duckchange.js"></script>