config/routes.rb
Rails.application.routes.draw do
  root 'duck#search'
	
  get 'match/showmatches'

  get 'match/showdetail'
  get 'match/showdetail/:id' => 'match#showdetail'

  get 'match/showreplay'

  post 'match/pondmatch' => 'match#singlefight'
  
  post 'match/fightover'

  get 'match/multifight'

  get 'match/loopfight'

  get 'duck/myscript'

  get 'duck/pondtest' => 'duck#createscript'
  
  get 'duck/editscript'
  
  get 'duck/editscript/:id' => 'duck#editscript'
  
  post 'duck/savescript'
  
  get 'duck/deletescript'
  get 'duck/deletescript/:id' => 'duck#deletescript'

  get 'duck/search'
  
  post 'duck/search' => 'duck#search_submit'

  get 'account/regist' => 'account#regist_new'
  
  post 'account/regist' => 'account#regist_submit'

  get 'account/login' => 'account#login_new'
  
  post 'account/login' => 'account#login_submit'

  get 'account/logout' 
  
  get 'account/info'
  get 'account/info/:id' => 'account#info'
  
  get 'account/changepw'
  post 'account/changepw' => 'account#changepw_submit'
  
  get 'account/editinfo' => 'account#info_edit'
  
  post 'account/editinfo' => 'account#info_submit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>  
<html>  
<head> 
 
  <title>池塘大战</title>  

  <%= csrf_meta_tags %>  

<%= javascript_include_tag "jquery.min","bootstrap.min",'data-turbolinks-track': 'reload' %>


<%= stylesheet_link_tag "bootstrap" , "AdminLTE.min", "_all-skins.min" , 'data-turbolinks-track': 'reload'%>

<style>
body { 
position: fixed;
			top: 0;
			left: 0;
			width: 100%;
			height: 100%;
			background: url(/images/bkg.jpg) no-repeat #000;
			background-size: cover;
			z-index: -1; 
			}
</style>

</head>  
<body class="hold-transition skin-blue sidebar-mini">  
  <header class="main-header">
    <!-- Logo -->
    <a href="<%= root_url %>" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>池塘</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>池塘大战</b></span>
    </a>
	

		
    <!-- Header Navbar: style can be found in header.less -->
	
	<% if session[:user_id] %>
    <nav class="navbar navbar-static-top">
	
		<div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
            <i class="fa fa-bars"></i>
          </button>
        </div>
		
              <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
          <ul class="nav navbar-nav">
		  <li><a href="<%=account_info_path%>"> <span>个人信息</span></a></li>
		  <li><a href="<%=duck_myscript_path%>"> <span>我的脚本</span></a></li>
		  <li><a href="<%=duck_pondtest_path%>"> <span>训练塘</span></a></li>
			<li><a href="<%=duck_search_path%>"> <span>开始对战</span></a></li>
			 
			 
			 <li><a href="<%=account_logout_path%>"> <span>登出</span></a></li>
			 <!--
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">

		 
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
			-->
          </ul>
        </div>
		
		

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
		  <!--
          <li class="dropdown messages-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-envelope-o"></i>
              <span class="label label-success">4</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">你有 4 条新信息</li>
              <li>
                <ul class="menu">
                  <li>
                    <a href="#">
                      <div class="pull-left">
                        <img src="<%=User.find_by(id: session[:user_id]).avatar%>" class="img-circle" alt="User Image">
                      </div>
                      <h4>
                        Support Team
                        <small><i class="fa fa-clock-o"></i> 5 mins</small>
                      </h4>
                    </a>
                  </li>
                  
                </ul>
              </li>
              <li class="footer"><a href="#">查看全部信息</a></li>
            </ul>
          </li>
          -->
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="<%=User.find_by(id: session[:user_id]).avatar%>" class="user-image" alt="User Image">
              <span class="hidden-xs"><%=session[:user_name] %></span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="<%=User.find_by(id: session[:user_id]).avatar%>" class="img-circle" alt="User Image">

                <p>
                  <%=session[:user_name] %>
                  <!-- <small>Member since Nov. 2012</small> -->
                </p>
              </li>
              <!-- Menu Body -->
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="<%= account_info_path %>" class="btn btn-default btn-flat">个人信息</a>
                </div>
                <div class="pull-right">
                  <a href="<%= account_logout_path %>" class="btn btn-default btn-flat">退出登录</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
	<% end %>
  </header>
    <div class="">  

        <div class="col-md-12">  
             <%= yield %>  
          </div><!--/row-->  

      </div><!--/row-->  

  
    </div><!--/.fluid-container-->  
  
    <!-- Le javascript  
    ================================================== -->  
    <!-- Placed at the end of the document so the pages load faster -->  
  
  </body>  
</html>  





  